# Generated by Django 5.2.5 on 2025-10-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useraccount_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_auth_profile_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
