# Generated by Django 5.2.5 on 2025-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLogModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateField()),
                ('api', models.CharField(help_text='API URL', max_length=1024)),
                ('headers', models.TextField()),
                ('body', models.TextField()),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('client_ip_address', models.CharField(max_length=50)),
                ('response', models.TextField()),
                ('status_code', models.SmallIntegerField(db_index=True, help_text='Response status code')),
                ('execution_time', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'db_table': 'api_log',
            },
        ),
    ]
